<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\AgentRun;
use App\Models\DataCase;
use App\Models\GlobalSetting;
use App\Services\PlannerService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class AgentExtendController extends Controller
{
    /**
     * Extend an existing agent run with new search steps generated by LLM.
     * POST /api/cases/{id}/agent/{runId}/extend
     */
    public function extend(
        Request $request,
        string $id,
        string $runId,
        PlannerService $planner
    ): JsonResponse {
        $case = DataCase::findOrFail($id);
        $run = AgentRun::where('case_id', $case->id)->where('id', $runId)->firstOrFail();

        $context = trim((string) $request->input('context', ''));
        if (empty($context)) {
            return response()->json(['error' => 'context required'], 400);
        }

        $state = $run->state ?? [];
        $plan = $state['plan'] ?? [];
        $steps = $plan['steps'] ?? [];

        // Generate new extension plan with case context to avoid redundant searches
        $extensionGoal = "Erweitere die Suche für '{$run->goal}'. Zusätzlicher Fokus: {$context}";
        $newPlan = $planner->createPlan(
            userGoal: $extensionGoal,
            maxResults: 100,
            caseId: $case->id
        );
        $newSteps = $newPlan['steps'] ?? [];

        // Append new steps
        $mergedSteps = array_merge($steps, $newSteps);
        $state['plan']['steps'] = $mergedSteps;
        $state['total_steps'] = count($mergedSteps);
        $state['logs'][] = [
            'timestamp' => now()->toIso8601String(),
            'message' => "Plan erweitert um " . count($newSteps) . " zusätzliche Schritte.",
        ];

        $run->update([
            'status' => 'running',
            'state' => $state,
        ]);

        return response()->json([
            'success' => true,
            'added_steps' => count($newSteps),
            'total_steps' => count($mergedSteps),
            'run' => $run,
            ...$run->toArray(),
        ]);
    }
}
