CREATE TABLE "apollo_cache" (
	"lookup_key" text PRIMARY KEY NOT NULL,
	"payload" jsonb NOT NULL,
	"fetched_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cases" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"ai_columns" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"api_key" text,
	"cerebras_api_key" text,
	"anthropic_api_key" text,
	"eden_api_key" text,
	"eden_region" text DEFAULT 'eu' NOT NULL,
	"model_allowlist" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"col_order" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"case_id" text NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rows" (
	"id" text PRIMARY KEY NOT NULL,
	"case_id" text NOT NULL,
	"row_index" integer NOT NULL,
	"data" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"cell_statuses" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"cell_errors" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scrape_cache" (
	"url" text PRIMARY KEY NOT NULL,
	"markdown" text NOT NULL,
	"title" text,
	"fetched_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "rows" ADD CONSTRAINT "rows_case_id_cases_id_fk" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_logs_case_id" ON "logs" USING btree ("case_id","id");--> statement-breakpoint
CREATE INDEX "idx_rows_case_id" ON "rows" USING btree ("case_id","row_index");