/**
 * lib/db.ts
 * PostgreSQL data layer via Drizzle ORM (postgres-js driver).
 *
 * LOCAL: brew services postgresql@17 + DATABASE_URL=postgres://<user>@localhost:5432/dataminer
 * CLOUD: any Postgres URL works unchanged (Neon, Supabase, RDS…).
 *
 * Schema is auto-pushed on first connection (drizzle push, safe/idempotent for dev).
 * All functions are async (postgres drivers are async by nature).
 */

import postgres from "postgres";
import { drizzle, type PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { sql, desc, asc, eq } from "drizzle-orm";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import fs from "fs";
import path from "path";
import type { Case, RowData, GroupedRowsResponse, CompanyGroup } from "./types";
import type { AgentRunState, AgentRunListItem } from "./agent-types";
import { decryptSecret, encryptSecret, maskSecret } from "./secrets";
import { cases, rows, logs, scrapeCache, apolloCache, settings, agentRuns } from "./db/schema";

// Re-export schema tables for scripts/migration tooling
export { cases, rows, logs, scrapeCache, apolloCache, settings, agentRuns };

const DEFAULT_URL = `postgres://${process.env.USER ?? "postgres"}@localhost:5432/dataminer`;
const databaseUrl = process.env.DATABASE_URL?.trim() || DEFAULT_URL;

let _db: PostgresJsDatabase | null = null;
let _client: postgres.Sql | null = null;
let _ready: Promise<void> | null = null;

export function getDb(): PostgresJsDatabase {
  if (!_db) {
    _client = postgres(databaseUrl, { max: 10, idle_timeout: 20, connect_timeout: 10 });
    _db = drizzle(_client);
  }
  return _db;
}

/** Ensures schema exists. Uses generated migrations when present, otherwise pushes schema. */
async function ensureSchema(client: postgres.Sql): Promise<void> {
  const migrationsDir = path.join(process.cwd(), "drizzle");
  const db = drizzle(client);
  if (fs.existsSync(path.join(migrationsDir, "meta", "_journal.json"))) {
    await migrate(db, { migrationsFolder: migrationsDir });
  } else {
    await client.unsafe(`
      CREATE TABLE IF NOT EXISTS cases (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        ai_columns JSONB NOT NULL DEFAULT '[]'::jsonb,
        api_key TEXT,
        cerebras_api_key TEXT,
        anthropic_api_key TEXT,
        eden_api_key TEXT,
        eden_region TEXT NOT NULL DEFAULT 'eu',
        model_allowlist JSONB NOT NULL DEFAULT '[]'::jsonb,
        col_order JSONB NOT NULL DEFAULT '[]'::jsonb,
        created_at TIMESTAMPTZ NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL
      );

      CREATE TABLE IF NOT EXISTS rows (
        id TEXT PRIMARY KEY,
        case_id TEXT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
        row_index INTEGER NOT NULL,
        data JSONB NOT NULL DEFAULT '{}'::jsonb,
        cell_statuses JSONB NOT NULL DEFAULT '{}'::jsonb,
        cell_errors JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_rows_case_id ON rows(case_id, row_index);

      CREATE TABLE IF NOT EXISTS logs (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        case_id TEXT NOT NULL,
        message TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_logs_case_id ON logs(case_id, id DESC);

      CREATE TABLE IF NOT EXISTS scrape_cache (
        url TEXT PRIMARY KEY,
        markdown TEXT NOT NULL,
        title TEXT,
        fetched_at TIMESTAMPTZ NOT NULL
      );

      CREATE TABLE IF NOT EXISTS apollo_cache (
        lookup_key TEXT PRIMARY KEY,
        payload JSONB NOT NULL,
        fetched_at TIMESTAMPTZ NOT NULL
      );

      CREATE TABLE IF NOT EXISTS settings (
        id TEXT PRIMARY KEY DEFAULT 'global',
        eden_api_key TEXT,
        eden_region TEXT NOT NULL DEFAULT 'eu',
        updated_at TIMESTAMPTZ NOT NULL
      );

      CREATE TABLE IF NOT EXISTS agent_runs (
        id TEXT PRIMARY KEY,
        case_id TEXT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
        goal JSONB NOT NULL,
        status TEXT NOT NULL DEFAULT 'planning',
        state JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_agent_runs_case_id ON agent_runs(case_id);
    `);
  }
}

/** Call once before any DB access (idempotent). */
export async function initDb(): Promise<void> {
  if (_ready) return _ready;
  getDb();
  _ready = ensureSchema(_client!).catch((e) => {
    _ready = null;
    throw e;
  });
  return _ready;
}

// ── Serialization helpers ────────────────────────────────────────────────────

function toIso(v: unknown): string {
  return v instanceof Date ? v.toISOString() : String(v ?? new Date().toISOString());
}

type CaseRow = typeof cases.$inferSelect;
type RowRow = typeof rows.$inferSelect;

function deserializeCase(row: CaseRow): Case {
  const edenApiKey = decryptSecret(row.edenApiKey ?? undefined);
  return {
    id: row.id,
    name: row.name,
    aiColumns: (row.aiColumns ?? []) as Case["aiColumns"],
    edenApiKey,
    edenApiKeyMasked: maskSecret(edenApiKey),
    edenRegion: row.edenRegion === "eu" ? "eu" : "us",
    modelAllowlist: (row.modelAllowlist ?? []) as string[],
    colOrder: (row.colOrder ?? []) as string[],
    createdAt: toIso(row.createdAt),
    updatedAt: toIso(row.updatedAt),
  };
}

function deserializeRow(row: RowRow): RowData {
  return {
    id: row.id,
    caseId: row.caseId,
    rowIndex: row.rowIndex,
    data: (row.data ?? {}) as RowData["data"],
    cellStatuses: (row.cellStatuses ?? {}) as RowData["cellStatuses"],
    cellErrors: (row.cellErrors ?? {}) as RowData["cellErrors"],
    createdAt: toIso(row.createdAt),
    updatedAt: toIso(row.updatedAt),
  };
}

// ── Cases ────────────────────────────────────────────────────────────────────

export async function listCases(): Promise<Case[]> {
  await initDb();
  const result = await getDb().select().from(cases).orderBy(desc(cases.updatedAt));
  return result.map(deserializeCase);
}

export async function getCase(id: string): Promise<Case | null> {
  await initDb();
  const result = await getDb().select().from(cases).where(eq(cases.id, id)).limit(1);
  return result[0] ? deserializeCase(result[0]) : null;
}

export async function createCase(c: Omit<Case, "createdAt" | "updatedAt">): Promise<Case> {
  await initDb();
  const now = new Date();
  await getDb()
    .insert(cases)
    .values({
      id: c.id,
      name: c.name,
      aiColumns: c.aiColumns ?? [],
      edenApiKey: encryptSecret(c.edenApiKey),
      edenRegion: c.edenRegion ?? "us",
      modelAllowlist: c.modelAllowlist ?? [],
      colOrder: c.colOrder ?? [],
      createdAt: now,
      updatedAt: now,
    });
  return (await getCase(c.id))!;
}

export async function updateCase(id: string, patch: Partial<Omit<Case, "id" | "createdAt">>): Promise<Case | null> {
  await initDb();
  const existing = await getCase(id);
  if (!existing) return null;
  const merged = { ...existing, ...patch, updatedAt: new Date().toISOString() };
  await getDb()
    .update(cases)
    .set({
      name: merged.name,
      aiColumns: merged.aiColumns ?? [],
      edenApiKey: encryptSecret(merged.edenApiKey),
      edenRegion: merged.edenRegion ?? "us",
      modelAllowlist: merged.modelAllowlist ?? [],
      colOrder: merged.colOrder ?? [],
      updatedAt: new Date(merged.updatedAt),
    })
    .where(eq(cases.id, id));
  return (await getCase(id))!;
}

/**
 * Effective Eden AI key: case-level key first, then EDEN_API_KEY env.
 * Eden AI is the only LLM provider — one key serves all models (provider/model IDs).
 * Pure function — no DB access, stays synchronous.
 */
export function getEffectiveApiKey(c: Case): string | undefined {
  return c.edenApiKey || process.env.EDEN_API_KEY || undefined;
}

// ── Global settings (single 'global' row) ───────────────────────────────

export interface GlobalSettings {
  edenApiKey?: string;
  edenApiKeyMasked?: string;
  edenRegion: "eu" | "us";
  modelAllowlist: string[];
  updatedAt: string;
}

const GLOBAL_SETTINGS_ID = "global";

export async function getGlobalSettings(): Promise<GlobalSettings> {
  await initDb();
  const result = await getDb()
    .select()
    .from(settings)
    .where(eq(settings.id, GLOBAL_SETTINGS_ID))
    .limit(1);
  const row = result[0];
  const key = row ? decryptSecret(row.edenApiKey ?? undefined) : undefined;
  return {
    edenApiKey: key,
    edenApiKeyMasked: maskSecret(key),
    edenRegion: row?.edenRegion === "eu" ? "eu" : "us",
    modelAllowlist: (row?.modelAllowlist as string[] | null) ?? [],
    updatedAt: row ? toIso(row.updatedAt) : new Date().toISOString(),
  };
}

/** Save global settings. An undefined/empty key clears the stored key. */
export async function saveGlobalSettings(patch: { edenApiKey?: string; edenRegion?: "eu" | "us"; modelAllowlist?: string[] }): Promise<GlobalSettings> {
  await initDb();
  const now = new Date();
  const region = patch.edenRegion === "eu" ? "eu" : "us";
  const encrypted = patch.edenApiKey !== undefined ? encryptSecret(patch.edenApiKey) : null;
  await getDb()
    .insert(settings)
    .values({
      id: GLOBAL_SETTINGS_ID,
      edenApiKey: encrypted,
      edenRegion: region,
      modelAllowlist: patch.modelAllowlist ?? [],
      updatedAt: now,
    })
    .onConflictDoUpdate({
      target: settings.id,
      set: {
        edenApiKey: patch.edenApiKey !== undefined ? encrypted : sql`${settings.edenApiKey}`,
        edenRegion: region,
        modelAllowlist: patch.modelAllowlist !== undefined ? patch.modelAllowlist : sql`${settings.modelAllowlist}`,
        updatedAt: now,
      },
    });
  return getGlobalSettings();
}

/**
 * Central key resolution — cascade: case key → global settings key → env.
 * Routes should call this instead of getEffectiveApiKey so a key entered once
 * on the global settings page works for every case.
 */
export async function resolveEdenKey(c?: Case | null): Promise<string | undefined> {
  if (c?.edenApiKey) return c.edenApiKey;
  const global = await getGlobalSettings();
  return global.edenApiKey || process.env.EDEN_API_KEY || undefined;
}

/** Central region resolution — cascade: case region → global region → "us" (default; EU lacks OpenAI models + Firecrawl web search). */
export async function resolveEdenRegion(c?: Case | null): Promise<"eu" | "us"> {
  if (c?.edenRegion === "us" || c?.edenRegion === "eu") return c.edenRegion;
  const global = await getGlobalSettings();
  return global.edenRegion;
}

export async function deleteCase(id: string): Promise<void> {
  await initDb();
  await getDb().delete(cases).where(eq(cases.id, id));
}

// ── Rows ─────────────────────────────────────────────────────────────────────

export async function listRows(caseId: string): Promise<RowData[]> {
  await initDb();
  const result = await getDb().select().from(rows).where(eq(rows.caseId, caseId)).orderBy(asc(rows.rowIndex));
  return result.map(deserializeRow);
}

/**
 * Grouped view: rows grouped by `data.company_name`.
 * First row per group = company, rest = contacts.
 * Pagination counts distinct companies, not individual rows.
 */
export async function listRowsGrouped(
  caseId: string,
  page = 1,
  perPage = 50,
): Promise<GroupedRowsResponse> {
  await initDb();
  const offset = (page - 1) * perPage;

  // Count distinct companies
  const countResult = await _client!.unsafe<[{ count: string }]>(
    `SELECT COUNT(DISTINCT data->>'company_name')::int as count FROM rows WHERE case_id = $1`,
    [caseId],
  );
  const totalCompanies = parseInt(countResult[0].count, 10);

  // Fetch paginated groups — one SQL query, groups server-side
  type GroupedRowRaw = { companyName: string | null; rowsJson: RowRow[] };
  const result = await _client!.unsafe<GroupedRowRaw[]>(
    `SELECT 
       data->>'company_name' as "companyName",
       json_agg(
         json_build_object(
           'id', id, 'caseId', case_id, 'rowIndex', row_index,
           'data', data, 'cellStatuses', cell_statuses, 'cellErrors', cell_errors,
           'createdAt', created_at, 'updatedAt', updated_at
         ) ORDER BY row_index ASC
       ) as "rowsJson"
     FROM rows
     WHERE case_id = $1
       AND data->>'company_name' IS NOT NULL
       AND data->>'company_name' <> ''
     GROUP BY data->>'company_name'
     ORDER BY MIN(row_index) ASC
     LIMIT $2 OFFSET $3`,
    [caseId, perPage, offset],
  );

  const companies: CompanyGroup[] = result.map((g) => {
    const rowObjs = (g.rowsJson as unknown as RowRow[]).map(deserializeRow);
    return {
      companyName: g.companyName ?? "",
      companyRow: rowObjs[0],
      contacts: rowObjs.slice(1),
    };
  });

  return { companies, totalCompanies, page, perPage };
}

export async function getRow(id: string): Promise<RowData | null> {
  await initDb();
  const result = await getDb().select().from(rows).where(eq(rows.id, id)).limit(1);
  return result[0] ? deserializeRow(result[0]) : null;
}

export async function upsertRow(r: RowData): Promise<RowData> {
  await initDb();
  const now = new Date();
  await getDb()
    .insert(rows)
    .values({
      id: r.id,
      caseId: r.caseId,
      rowIndex: r.rowIndex,
      data: r.data ?? {},
      cellStatuses: r.cellStatuses ?? {},
      cellErrors: r.cellErrors ?? {},
      createdAt: new Date(r.createdAt || now),
      updatedAt: now,
    })
    .onConflictDoUpdate({
      target: rows.id,
      set: {
        data: r.data ?? {},
        cellStatuses: r.cellStatuses ?? {},
        cellErrors: r.cellErrors ?? {},
        updatedAt: now,
      },
    });
  return (await getRow(r.id))!;
}

/**
 * Update a single key inside a row's JSONB data + statuses without a read-modify-write
 * round trip (atomic, concurrency-safe — important for parallel column runs).
 */
export async function updateRowCell(rowId: string, outputKey: string, value: string, status: string, error?: string): Promise<void> {
  await initDb();
  const db = getDb();
  // Explicit ::text casts on the key params — Postgres cannot infer parameter
  // types inside jsonb_build_object from bind placeholders alone.
  await db
    .update(rows)
    .set({
      data: sql`${rows.data} || jsonb_build_object(${outputKey}::text, ${value}::text)`,
      cellStatuses: sql`${rows.cellStatuses} || jsonb_build_object(${outputKey}::text, ${status}::text)`,
      cellErrors: sql`CASE WHEN ${error ?? null}::text IS NULL
        THEN ${rows.cellErrors} - ${outputKey}::text
        ELSE ${rows.cellErrors} || jsonb_build_object(${outputKey}::text, ${error ?? ""}::text) END`,
      updatedAt: new Date(),
    })
    .where(eq(rows.id, rowId));
}

export async function deleteRow(id: string): Promise<void> {
  await initDb();
  await getDb().delete(rows).where(eq(rows.id, id));
}

export async function deleteRowsByCase(caseId: string): Promise<void> {
  await initDb();
  await getDb().delete(rows).where(eq(rows.caseId, caseId));
}

export async function bulkInsertRows(newRows: RowData[]): Promise<void> {
  if (newRows.length === 0) return;
  await initDb();
  // All-or-nothing: chunked inserts run inside a single transaction
  await getDb().transaction(async (tx) => {
    await bulkInsertRowsWith(tx as unknown as PostgresJsDatabase, newRows);
  });
}

async function bulkInsertRowsWith(executor: PostgresJsDatabase, newRows: RowData[]): Promise<void> {
  if (newRows.length === 0) return;
  const now = new Date();
  // Chunk to stay within statement size limits
  const CHUNK = 500;
  for (let i = 0; i < newRows.length; i += CHUNK) {
    const chunk = newRows.slice(i, i + CHUNK);
    const values = chunk.map((r) => ({
      id: r.id,
      caseId: r.caseId,
      rowIndex: r.rowIndex,
      data: r.data ?? {},
      cellStatuses: r.cellStatuses ?? {},
      cellErrors: r.cellErrors ?? {},
      createdAt: new Date(r.createdAt || now),
      updatedAt: now,
    }));
    await executor
      .insert(rows)
      .values(values)
      .onConflictDoUpdate({
        target: rows.id,
        // mirror old SQLite behaviour: conflicting rows get fresh data
        set: { data: sql`excluded.data`, updatedAt: sql`excluded.updated_at` },
      });
  }
}

// ── Discovery helpers ────────────────────────────────────────────────────────

/** Highest row_index in a case (-1 when empty). Used to append discovered rows. */
export async function getMaxRowIndex(caseId: string): Promise<number> {
  await initDb();
  return getMaxRowIndexWith(getDb(), caseId);
}

async function getMaxRowIndexWith(executor: PostgresJsDatabase, caseId: string): Promise<number> {
  const result = await executor
    .select({ maxIdx: sql<number | null>`MAX(${rows.rowIndex})` })
    .from(rows)
    .where(eq(rows.caseId, caseId));
  const v = result[0]?.maxIdx;
  return v == null ? -1 : Number(v);
}

/**
 * All normalised domains already present in a case. Every row may contribute
 * MULTIPLE domains — `source_domain`, `official_domain` and `domain` are all
 * collected (one row can legitimately know a company under several domains).
 * Uses PG unnest + jsonb operators — no full-row transfer needed.
 */
export async function getExistingDomains(caseId: string): Promise<string[]> {
  await initDb();
  return getExistingDomainsWith(getDb(), caseId);
}

async function getExistingDomainsWith(executor: PostgresJsDatabase, caseId: string): Promise<string[]> {
  const raw = await executor.execute(sql`
    SELECT DISTINCT LOWER(
      REGEXP_REPLACE(
        REGEXP_REPLACE(
          REGEXP_REPLACE(v.val, '^https?://', ''),
          '^www\\.', ''
        ), '/.*$', ''
      )
    ) AS domain
    FROM ${rows},
    LATERAL unnest(ARRAY[
      ${rows.data}->>'source_domain',
      ${rows.data}->>'official_domain',
      ${rows.data}->>'domain'
    ]) AS v(val)
    WHERE ${rows.caseId} = ${caseId} AND v.val IS NOT NULL AND v.val <> ''
  `);
  // postgres-js returns the row list directly; normalise defensively
  const arr: unknown[] = Array.isArray(raw) ? raw : ((raw as { rows?: unknown[] }).rows ?? []);
  const domains = new Set<string>();
  for (const r of arr as Array<{ domain: string | null }>) {
    const d = String(r.domain ?? "").trim();
    if (d.includes(".")) domains.add(d);
  }
  return Array.from(domains);
}

/**
 * Append discovery seed rows to a case, skipping duplicate domains (both
 * against existing rows and within the batch). Runs in a single transaction
 * holding a FOR UPDATE lock on the parent case so two concurrent discovery
 * imports cannot both pass the duplicate check (no race-written duplicates).
 */
export async function appendDiscoveryRows(
  caseId: string,
  seeds: RowData[]
): Promise<{ inserted: number; duplicates: number }> {
  await initDb();
  const db = getDb();
  return await db.transaction(async (tx) => {
    const executor = tx as unknown as PostgresJsDatabase;
    await executor.execute(sql`SELECT id FROM ${cases} WHERE id = ${caseId} FOR UPDATE`);

    const existingDomains = new Set(await getExistingDomainsWith(executor, caseId));

    // Also load existing _parent_row_id values to avoid duplicate contact rows
    const existingRows = await executor.select({ data: rows.data }).from(rows)
      .where(eq(rows.caseId, caseId));
    const existingParentIds = new Set(
      existingRows
        .map(r => (r.data as Record<string, string>)["_parent_row_id"])
        .filter(Boolean)
    );

    const maxIdx = await getMaxRowIndexWith(executor, caseId);
    let duplicates = 0;
    const toInsert: RowData[] = [];
    let nextIdx = maxIdx + 1;

    for (const seed of seeds) {
      const data = seed.data as Record<string, string>;

      // Check for contact row duplicate by parent
      if (data["_parent_row_id"] && existingParentIds.has(data["_parent_row_id"])) {
        duplicates++;
        continue;
      }

      // Check domain duplicate (try both domain and source_domain fields)
      const domain = (data["domain"] ?? data["source_domain"] ?? "").toLowerCase().trim();
      if (domain && existingDomains.has(domain)) {
        duplicates++;
        continue;
      }

      if (domain) existingDomains.add(domain);
      if (data["_parent_row_id"]) existingParentIds.add(data["_parent_row_id"]);
      toInsert.push({ ...seed, rowIndex: nextIdx++ });
    }

    if (toInsert.length > 0) await bulkInsertRowsWith(executor, toInsert);
    return { inserted: toInsert.length, duplicates };
  });
}

// ── Logs ─────────────────────────────────────────────────────────────────────

export async function appendLog(caseId: string, message: string): Promise<void> {
  await initDb();
  await getDb().insert(logs).values({ caseId, message, createdAt: new Date() });
}

export async function getLogs(caseId: string, limit = 200): Promise<{ id: number; message: string; createdAt: string }[]> {
  await initDb();
  const result = await getDb()
    .select({ id: logs.id, message: logs.message, createdAt: logs.createdAt })
    .from(logs)
    .where(eq(logs.caseId, caseId))
    .orderBy(desc(logs.id))
    .limit(limit);
  return result.map((r) => ({ id: r.id, message: r.message, createdAt: toIso(r.createdAt) })).reverse();
}

export async function clearLogs(caseId: string): Promise<void> {
  await initDb();
  await getDb().delete(logs).where(eq(logs.caseId, caseId));
}

// ── Scrape cache ─────────────────────────────────────────────────────────────

const SCRAPE_CACHE_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

export async function getCachedScrape(url: string): Promise<{ markdown: string; title?: string } | null> {
  await initDb();
  const result = await getDb()
    .select({ markdown: scrapeCache.markdown, title: scrapeCache.title, fetchedAt: scrapeCache.fetchedAt })
    .from(scrapeCache)
    .where(eq(scrapeCache.url, url))
    .limit(1);
  const row = result[0];
  if (!row) return null;
  const age = Date.now() - new Date(row.fetchedAt).getTime();
  if (Number.isFinite(age) && age > SCRAPE_CACHE_TTL_MS) return null;
  return { markdown: row.markdown, title: row.title ?? undefined };
}

export async function setCachedScrape(url: string, markdown: string, title?: string): Promise<void> {
  await initDb();
  await getDb()
    .insert(scrapeCache)
    .values({ url, markdown, title: title ?? null, fetchedAt: new Date() })
    .onConflictDoUpdate({
      target: scrapeCache.url,
      set: { markdown, title: title ?? null, fetchedAt: new Date() },
    });
}

// ── Apollo cache ─────────────────────────────────────────────────────────────

const APOLLO_CACHE_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days — saves paid lookups

export async function getApolloCache(lookupKey: string): Promise<unknown | null> {
  await initDb();
  const result = await getDb()
    .select({ payload: apolloCache.payload, fetchedAt: apolloCache.fetchedAt })
    .from(apolloCache)
    .where(eq(apolloCache.lookupKey, lookupKey))
    .limit(1);
  const row = result[0];
  if (!row) return null;
  const age = Date.now() - new Date(row.fetchedAt).getTime();
  if (Number.isFinite(age) && age > APOLLO_CACHE_TTL_MS) return null;
  return row.payload ?? null;
}

export async function setApolloCache(lookupKey: string, payload: unknown): Promise<void> {
  await initDb();
  await getDb()
    .insert(apolloCache)
    .values({ lookupKey, payload: payload ?? null, fetchedAt: new Date() })
    .onConflictDoUpdate({
      target: apolloCache.lookupKey,
      set: { payload: payload ?? null, fetchedAt: new Date() },
    });
}

// ── Agent runs ───────────────────────────────────────────────────────────────

export async function createAgentRun(run: AgentRunState): Promise<void> {
  await initDb();
  await getDb().insert(agentRuns).values({
    id: run.id,
    caseId: run.caseId,
    goal: run.goal as unknown as Record<string, unknown>,
    status: run.status,
    state: run as unknown as Record<string, unknown>,
    createdAt: new Date(run.startedAt),
    updatedAt: new Date(run.updatedAt),
  });
}

export async function getAgentRun(runId: string): Promise<AgentRunState | null> {
  await initDb();
  const rows_ = await getDb()
    .select()
    .from(agentRuns)
    .where(eq(agentRuns.id, runId))
    .limit(1);
  const row = rows_[0];
  if (!row) return null;
  return row.state as unknown as AgentRunState;
}

export async function updateAgentRunState(run: AgentRunState): Promise<void> {
  await initDb();
  await getDb()
    .update(agentRuns)
    .set({
      status: run.status,
      state: run as unknown as Record<string, unknown>,
      updatedAt: new Date(run.updatedAt),
    })
    .where(eq(agentRuns.id, run.id));
}

export async function listAgentRuns(caseId: string): Promise<AgentRunListItem[]> {
  await initDb();
  const result = await getDb()
    .select({
      id: agentRuns.id,
      status: agentRuns.status,
      state: agentRuns.state,
      createdAt: agentRuns.createdAt,
    })
    .from(agentRuns)
    .where(eq(agentRuns.caseId, caseId))
    .orderBy(desc(agentRuns.createdAt))
    .limit(50);

  return result.map((r) => {
    const s = r.state as Record<string, unknown>;
    const goal = s.goal as Record<string, unknown> | undefined;
    return {
      id: r.id,
      goal: typeof goal?.description === "string" ? goal.description : "",
      status: r.status as AgentRunListItem["status"],
      targetCount: typeof goal?.targetCount === "number" ? goal.targetCount : 0,
      uniqueCount: typeof s.uniqueCount === "number" ? s.uniqueCount as number : 0,
      startedAt: toIso(r.createdAt),
    };
  });
}
