/**
 * scripts/migrate-sqlite-to-pg.ts
 * One-shot migration: SQLite (data/dataminer.db) → PostgreSQL.
 *
 * Run:  npx tsx scripts/migrate-sqlite-to-pg.ts
 * Env:  DATABASE_URL (default postgres://<user>@localhost:5432/dataminer)
 *
 * Copies cases, rows, logs, scrape_cache, apollo_cache. Idempotent via
 * upserts (ON CONFLICT DO UPDATE). The old SQLite file is left untouched.
 */

import Database from "better-sqlite3";
import postgres from "postgres";
import fs from "fs";
import path from "path";

const SQLITE_PATH = path.join(process.cwd(), "data", "dataminer.db");
const DEFAULT_URL = `postgres://${process.env.USER ?? "postgres"}@localhost:5432/dataminer`;
const PG_URL = process.env.DATABASE_URL?.trim() || DEFAULT_URL;

function toTs(iso: string | null | undefined): Date {
  if (!iso) return new Date();
  const d = new Date(iso);
  return Number.isFinite(d.getTime()) ? d : new Date();
}

async function main() {
  if (!fs.existsSync(SQLITE_PATH)) {
    console.log(`No SQLite file at ${SQLITE_PATH} — nothing to migrate.`);
    return;
  }

  const sqlite = new Database(SQLITE_PATH, { readonly: true });
  const pg = postgres(PG_URL, { max: 1 });

  console.log(`Migrating ${SQLITE_PATH} → ${PG_URL.replace(/:[^@]*@/, ":***@")}`);

  // Schema is created on demand by lib/db.ts (initDb); ensure it exists here too
  await pg.unsafe(`
    CREATE TABLE IF NOT EXISTS cases (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      ai_columns JSONB NOT NULL DEFAULT '[]'::jsonb,
      api_key TEXT,
      cerebras_api_key TEXT,
      anthropic_api_key TEXT,
      eden_api_key TEXT,
      eden_region TEXT NOT NULL DEFAULT 'eu',
      model_allowlist JSONB NOT NULL DEFAULT '[]'::jsonb,
      col_order JSONB NOT NULL DEFAULT '[]'::jsonb,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL
    );
    CREATE TABLE IF NOT EXISTS rows (
      id TEXT PRIMARY KEY,
      case_id TEXT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
      row_index INTEGER NOT NULL,
      data JSONB NOT NULL DEFAULT '{}'::jsonb,
      cell_statuses JSONB NOT NULL DEFAULT '{}'::jsonb,
      cell_errors JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_rows_case_id ON rows(case_id, row_index);
    CREATE TABLE IF NOT EXISTS logs (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      case_id TEXT NOT NULL,
      message TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_logs_case_id ON logs(case_id, id DESC);
    CREATE TABLE IF NOT EXISTS scrape_cache (
      url TEXT PRIMARY KEY,
      markdown TEXT NOT NULL,
      title TEXT,
      fetched_at TIMESTAMPTZ NOT NULL
    );
    CREATE TABLE IF NOT EXISTS apollo_cache (
      lookup_key TEXT PRIMARY KEY,
      payload JSONB NOT NULL,
      fetched_at TIMESTAMPTZ NOT NULL
    );
  `);

  const safeJson = (s: unknown, fallback: unknown) => {
    try {
      return s == null || s === "" ? fallback : JSON.parse(String(s));
    } catch {
      return fallback;
    }
  };

  // ── cases ──
  const cases = sqlite.prepare("SELECT * FROM cases").all() as any[];
  for (const c of cases) {
    await pg`
      INSERT INTO cases (id, name, ai_columns, api_key, cerebras_api_key, anthropic_api_key, eden_api_key, eden_region, model_allowlist, col_order, created_at, updated_at)
      VALUES (${c.id}, ${c.name}, ${pg.json(safeJson(c.ai_columns, []))}, ${c.api_key}, ${c.cerebras_api_key}, ${c.anthropic_api_key}, ${c.eden_api_key}, ${c.eden_region ?? "eu"}, ${pg.json(safeJson(c.model_allowlist, []))}, ${pg.json(safeJson(c.col_order, []))}, ${toTs(c.created_at)}, ${toTs(c.updated_at)})
      ON CONFLICT (id) DO NOTHING
    `;
  }
  console.log(`  cases: ${cases.length}`);

  // ── rows (bulk in chunks) ──
  const rows = sqlite.prepare("SELECT * FROM rows").all() as any[];
  const CHUNK = 500;
  for (let i = 0; i < rows.length; i += CHUNK) {
    await pg.begin(async (tx) => {
      for (const r of rows.slice(i, i + CHUNK)) {
        await tx`
          INSERT INTO rows (id, case_id, row_index, data, cell_statuses, cell_errors, created_at, updated_at)
          VALUES (${r.id}, ${r.case_id}, ${r.row_index}, ${tx.json(safeJson(r.data, {}))}, ${tx.json(safeJson(r.cell_statuses, {}))}, ${tx.json(safeJson(r.cell_errors, {}))}, ${toTs(r.created_at)}, ${toTs(r.updated_at)})
          ON CONFLICT (id) DO NOTHING
        `;
      }
    });
  }
  console.log(`  rows: ${rows.length}`);

  // ── logs ──
  const logs = sqlite.prepare("SELECT * FROM logs ORDER BY id ASC").all() as any[];
  for (const l of logs) {
    await pg`
      INSERT INTO logs (case_id, message, created_at)
      VALUES (${l.case_id}, ${l.message}, ${toTs(l.created_at)})
    `;
  }
  console.log(`  logs: ${logs.length}`);

  // ── scrape_cache ──
  const scrapes = sqlite.prepare("SELECT * FROM scrape_cache").all() as any[];
  for (const s of scrapes) {
    await pg`
      INSERT INTO scrape_cache (url, markdown, title, fetched_at)
      VALUES (${s.url}, ${s.markdown}, ${s.title}, ${toTs(s.fetched_at)})
      ON CONFLICT (url) DO NOTHING
    `;
  }
  console.log(`  scrape_cache: ${scrapes.length}`);

  // ── apollo_cache ──
  const apollo = sqlite.prepare("SELECT * FROM apollo_cache").all() as any[];
  for (const a of apollo) {
    await pg`
      INSERT INTO apollo_cache (lookup_key, payload, fetched_at)
      VALUES (${a.lookup_key}, ${pg.json(safeJson(a.payload, null))}, ${toTs(a.fetched_at)})
      ON CONFLICT (lookup_key) DO NOTHING
    `;
  }
  console.log(`  apollo_cache: ${apollo.length}`);

  const counts = (await pg`SELECT
    (SELECT COUNT(*) FROM cases) AS cases,
    (SELECT COUNT(*) FROM rows) AS rows,
    (SELECT COUNT(*) FROM logs) AS logs`)[0];
  console.log(`\nDone. Postgres now has: ${counts.cases} cases, ${counts.rows} rows, ${counts.logs} logs.`);

  sqlite.close();
  await pg.end();
}

main().catch((e) => {
  console.error("Migration failed:", e);
  process.exit(1);
});
